### ISSUE TITLE
Get the list of servers from proXPN servers

### ISSUE THREAD

**Issue by ghost** [MattSurabian/proxpn-bash-client#2]
Silly me I didn't check github before working on my script. It turns out I have ended up doing the same thing as you (dough!).

Anyway, the only difference is that I found out that the Windows/MAC clients are downloading the list of servers from proXPN web page each time, so that they can keep it up to date instead of having to rely on a static list.

It would be a nive improvement to also have this in your script (however the XML parsing in bash might be a bit too much...). Here is how I did it in python in case you find it useful: https://github.com/bocadillodeatun/proxpn_python_client

Anyway, thanks for the script! :)

**Comment by MattSurabian** [comment]
Thanks for this! I know they added a few endpoints since I asked them for a list, but hadn't gotten around to asking for an update. 

The XML parsing in bash is definitely too much, ultimately I like the fact that the bash implementation keeps dependencies to a minimum and doesn't need to ask remote nodes for any information in order to run. That said, I have been considering writing a cross platform client in Go since binaries could be shipped, I'm just not sure how that would go over with the security minded folks that like things transparent. 

I took a look at your python implementation and it seems pretty solid to me :+1: the more the merrier :smiley:

**Comment by hhutchin** [comment]
This is great, man. What you have done here is really great. But, I wanted to draw your attention to something that may not have been around 6 months ago when you started this.  After I got  your bash all working I started looking for an updated endpoint lists to include. I didn't find that, but i did find this: https://support.proxpn.com/customer/en/portal/articles/2120656-linux-install-instructions . its an 'unsupported' linux package provided by proxpn. It didn't take to much work to get it working with my distro. It's got a fancy gui and everything.

**Comment by TheSageMarmot** [comment]
If I can get some time, I'd like to contribute. This script was helpful to me because I needed to connect from a headless server and didn't like adding some unofficial binaries from proxpn. I'm more familiar with bash than python. I'm glad to see people sharing their work.

**Comment by MattSurabian** [comment]
Thanks for letting me know about that @hhutchin! You're right that wasn't around when I developed this. Though, I'm on Arch so a `.deb` doesn't really solve my use case anyway.

**Comment by MattSurabian** [comment]
Glad this was helpful, @TheSageMarmot

**Comment by MattSurabian** [comment]
I'm going to close this issue but would love to continue the discussion about retrieving exit nodes, IPs vs. DNS, etc in #3.
