### ISSUE TITLE
Increase privacy against DNS server

### ISSUE THREAD

**Issue by e-t-u** [MattSurabian/proxpn-bash-client#29]
I would like to suggest that the script makes DNS searches for all the servers and then establishes connection using IP address of the selected server. Then the DNS server is not able to find out to which server you are going to connect.

**Comment by MattSurabian** [comment]
I think this makes for an interesting discussion point especially in light of #25. 

My thought has always been that this script should not make any unsecured network communications as part of its run. Implementing a feature like this would introduce the need for in the clear requests for the IP. There's no guarantee of accuracy if the client's DNS servers are used because it's possible their DNS is being monitored or otherwise controlled. That would mean the script would have to make the connection to some "trusted" third party DNS. The two likely candidates there would be OpenDNS and GoogleDNS but unfortunately each bring pros and cons depending on the views of the script's users.

In the past there was discussion around using IPs in the script. The trouble then is that adopters are left with mystery meat.

My workaround suggestion would be that maybe we publish the IPs and users can setup something in `/etc/hosts` or similar to ensure a direct IP connection happens without the need for a DNS request at all.

Happy to further discuss pros and cons of this feature and if folks want it I don't have a problem adding it.

**Comment by e-t-u** [comment]
I went through all sources mentioning proxpn servers, checked that they existed in DNS and tested them. It left seven working servers and four servers mentioned in Mac sources did not work - so they likely are temporarily down. I also checked internet Maps where the servers are and there were couple of surprises, especiallly in Miami. The working servers are: Costa Rica, Edison, LA, NL, Seattle, Sweden and UK. The servers in Mac sources that did not work now are: Dallas, Miami, NYC and Singapore.

The servers that were not mentioned in Mac sources and they do not work, but they have DNS and they can be found from IP address maps in proper places: Chech (not in Prague), Beverly Hills, Chile, Dallas2, Japan, NL2 and 3, NYC2, Plano, SG2.

In historical documents there are pretty many places where there are not even DNS any more. For example Australia and India.

I created an /etc/hosts file that contains all the names I found from DNS. It comments where they are and if they worked. Likely not all the names are servers at all.

I have not tested this yet as a real hosts file.

I also figured out how to create Gnome NetworkManager entries out of these hosts, if someone is interested.

[proxpn.hosts.txt](https://github.com/MattSurabian/proxpn-bash-client/files/129498/proxpn.hosts.txt)

**Comment by e-t-u** [comment]
I quicly document here how to add entries to Gnome NetworkManager before I forget how to do that...

VPNs are in /etc/NetworkManager/system-connections. I have included a file that works for me there (my passwords removed, put yours there). Note that certificates must be in such a place that selinux accepts it as proper place for certificates like ~/.cert/, fix that place to the configuration file instead of "/home/etu/.cert". You can get needed three certificates from Mac distribution (ca.crt, client.crt, client.key).

When you have added your credentials and tested, you can copy that to all the servers and change just server name and address. But there is a trick: UUID must be unique.

I used this to change to random UUID:

`sed -ri "s/uuid=(.*)/uuid=`uuidgen`/" CONFFILENAME
`
(uuidgen in backquotes... this smart system removes them. It is a pretty standard Linux program that generates random UUIDs.)

and then the networking must be restarted to get changes to the VPN menu, in my Fedora:

`service network restart
`
It complains, but it works.

(The configuration file does not need to end to .txt, I just had to rename it for importing here)

[proxpn Edison.txt](https://github.com/MattSurabian/proxpn-bash-client/files/129507/proxpn.Edison.txt)

**Comment by MattSurabian** [comment]
I have been sick and haven't had time to grok your updates here. I'll take a look in the next couple of days. Sorry for the delay!

**Comment by MattSurabian** [comment]
I've come around to using IPs which are scraped from http://proxpn.com/updater/locations-v3.xml and added into the script. This should increase privacy with regard to DNS requests as you initially requested.

I used to worry that the IPs would just be mystery meat, but being able to document the XML file they come from as provided by ProXPN seems fine. This will land with the UDP work.
