### ISSUE TITLE
Network Manager OVPN file

### ISSUE THREAD

**Issue by jdferron** [MattSurabian/proxpn-bash-client#36]
Hi Matt,

Thank you for creating this!   Have you thought of creating on ovpn file which is compatible with network manager?  I ask because while I could use bash client to connect to openvpn, having the network manager version would be easier.

Any thoughts?  Thanks!

**Comment by MattSurabian** [comment]
I haven't played around with this too much but am not opposed to doing something to support Network Manager, even if it would be in a different repo. I run Arch Linux as my daily driver and use Network Manager so I can tool around with this. Have you done any experimentation yet?

**Comment by jdferron** [comment]
I've tried.  I had it working in Ubuntu on an old HD.  I have to get an external HD case as it is not my primary HD anymore.  Though I'm not sure it'll boot on my current laptop.

I'm running a Ubuntu based OS from chromebooks (GalliumOS).  I seem to have forgotten how to re-create it/didn't save the prior instructions..

**Comment by jdferron** [comment]
Matt,

I was able to successfully create a vpn connection via UDP to ProXPN.  For some reason it is not liking TCP based connections.  Not sure why.

**Comment by MattSurabian** [comment]
Could you post up what you did to get this working for UDP? I haven't had a chance to play with this at all

**Comment by MattSurabian** [comment]
It looks like the latest version of Network Manager will work with ovpn files. You'll have to specify the remote, protocol, and auth information that are normally in the output of the cli run but otherwise it should work out of the box.

I'm open to adding commented out lines in the ovpn file if folks think it would be helpful otherwise I'm lately thinking this may be out of scope and better served by a gist or repo with just that file in it.
