### ISSUE TITLE
OpenVPN using ProXPN

### ISSUE THREAD

**Issue by WUUUUTTT** [MattSurabian/proxpn-bash-client#43]
I'm not sure if this is exactly the right place to post this so I apologize if that's the case however I noticed ProXPN now provides their certs and OpenVPN setup instructions on the site.  

Setup proXPN on Linux using Network Manager
Following steps have been verified on Ubuntu 15.10
Open terminal and run
sudo apt-get install network-manager-openvpn
On Network Connections, click Edit Connections
Click Add button

Select OpenVPN from Connection Type list

Then click Create... button:

On Editing VPN Connection, fill in your username and password, and proXPN servers as following
Click Advanced... button, then under General tab, check following check boxes 
click Security tab, select BF-CBC with keysize 512

Our certificates and key are available at here ca.crt, client.crt, client.key. Right click and select Save As.

I've tried these steps and the service stops or times out.  Not sure what the deal is....

**Comment by MattSurabian** [comment]
Sorry about that not working. I can't really provide support for their website content and can't say for sure what's going on there. Checkout issue #36 as it would seem the latest version of network manager supports ovpn files out of the box which should mean using the ovpn file in this repo may work with minimal modification.

I'm closing this since it's not related to the bash client, but it would be a great help if you could provide a link to the proxpn page where the content above lives in issue #36. It might help move the network manager support piece along which would at the same solve this issue for you.
