### ISSUE TITLE
Unable to connect - process restarts

### ISSUE THREAD

**Issue by ramkumarkr** [MattSurabian/proxpn-bash-client#55]
Until I found this repo, I have had trouble configuring ProXPN, but now it looks like installation is completed, but having initial connection challenges.

Here are the output lines from console, I picked something which are repeating. Could you please help me in finding what I may be missing? I am only on a Proxpn basic account. Has it to do something with that?

Mon Mar  5 11:45:40 2018 us=67497 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Mon Mar  5 11:45:40 2018 us=67644 TCP/UDP: Preserving recently used remote address: [AF_INET]107.6.100.3:443
Mon Mar  5 11:45:40 2018 us=67983 Socket Buffers: R=[163840->163840] S=[163840->163840]
Mon Mar  5 11:45:40 2018 us=68173 UDP link local: (not bound)
**Mon Mar  5 11:45:40 2018 us=68361 UDP link remote: [AF_INET]107.6.100.3:443
Mon Mar  5 11:46:40 2018 us=37922 TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
Mon Mar  5 11:46:40 2018 us=38104 TLS Error: TLS handshake failed
Mon Mar  5 11:46:40 2018 us=38809 TCP/UDP: Closing socket
Mon Mar  5 11:46:40 2018 us=39087 SIGUSR1[soft,tls-error] received, process restarting**
Mon Mar  5 11:46:40 2018 us=39368 Restart pause, 5 second(s)
Mon Mar  5 11:46:45 2018 us=39649 Re-using SSL/TLS context
Mon Mar  5 11:46:45 2018 us=39840 LZO compression initializing
Mon Mar  5 11:46:45 2018 us=40453 Control Channel MTU parms [ L:1622 D:1212 EF:38 EB:0 ET:0 EL:3 ]
Mon Mar  5 11:46:45 2018 us=40719 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
Mon Mar  5 11:46:45 2018 us=41014 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-client'
Mon Mar  5 11:46:45 2018 us=41160 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1542,tun-mtu 1500,proto UDPv4,comp-lzo,cipher BF-CBC,auth SHA1,keysize 512,key-method 2,tls-server'
Mon Mar  5 11:46:45 2018 us=41374 TCP/UDP: Preserving recently used remote address: [AF_INET]107.6.100.3:443
Mon Mar  5 11:46:45 2018 us=41720 Socket Buffers: R=[163840->163840] S=[163840->163840]
Mon Mar  5 11:46:45 2018 us=41870 UDP link local: (not bound)
Mon Mar  5 11:46:45 2018 us=42019 UDP link remote: [AF_INET]107.6.100.3:443

**Comment by MattSurabian** [comment]
There are a couple of reasons this could be happening. It's hard to say which is to blame without more information. Some thoughts:
  * Did you use the installer in this repo? Are you sure you have a `~/.config/proxpn/proxpn.ovpn` file? That file contains the proxpn client TLS certs OpenVPN needs in order to establish a connection with ProXPN, without those you'll get TLS errors.
  * You mention you have a free account, are you using the `FREE` exit node option with UDP? What exit node are you trying to connect to and over which protocol?
  * What version of OpenVPN and OpenSSL are you running? `openvpn --version` I'm running OpenVPN 2.4.4 and OpenSSL 1.1.0g If your versions are REALLY old (not just a little) maybe your machine isn't supporting the cipher suites the service requires

**Comment by ramkumarkr** [comment]
Thanks for the response!
The FREE exit node selection was the point. It looks like connected.

**Comment by MattSurabian** [comment]
Glad to hear you got it sorted out! Cheers!
